# Part 107 Experience

*by Megan Phillips*

## Preparation

If you are preparing for the Part 107 exam, there are numerous ways to study that will be beneficial. The methods that I found the most useful were to first go over the material given in the [FAA sUAS study guide](https://www.faa.gov/sites/faa.gov/files/regulations_policies/handbooks_manuals/aviation/remote_pilot_study_guide.pdf) to begin understanding all of the rules and regulations required for the exam. This study guide breaks down almost everything that can be seen on the test. After gaining a solid framework, I recommend testing your knowledge and going through some practice tests to begin seeing what topics you know well and what topics you may be struggling with. The practice tests I used were the:

1. [The FAA Sample Questions](https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/uag_questions.pdf)

    a. These are real test questions that have been used in the past on the Part 107 Exam and will most likely be very similar to the current questions being used.

2. [Half Chrome FAA Part 107 Test Walkthrough Video](https://www.youtube.com/watch?v=AlKpzVY8FZM)

    a. This is a video that goes through the FAA sample questions (1), gives you the correct answers, and explains the reasoning for that answer and why the other answers are incorrect.

3. [Drone Law and Drone Attorney Assistance Test](https://jrupprechtlaw.com/part-107-knowledge-test/)

    a. This website teaches you the legal aspects of drone flying and helps you understand what each law entails. It gives you sample questions similar to those in (1) and then explains why your chosen answer is correct or incorrect based on the law it applies to.

4. There are also other videos and articles online that may be useful for explaining specific
things such as the METAR and TAF reports.

Once you are ready to schedule your exam you can follow [How to Schedule Your FAA Part 107](https://www.peltierphotocourses.com/pages/schedule-part-107-remote-pilot-test).


## Experience:

On the day before my exam, I received an email confirming my exam and the details concerning it, including location, time, documents to bring, etc. On my test day when I walked into the facility, I followed the signs posted and then I was greeted by my exam proctor who confirmed my information and asked for my documents to complete the paperwork. After this was complete, she handed me a basket to put my belongings in and then put them in a locked cabinet and took me and the other testers into the exam room and told us all of the rules and what we were to do if we have a question or when we are completed. During the test, you are given 120 minutes to take 60 questions, however, the exam only took me about an hour. You are given the [FAA Chart Supplement](https://www.faa.gov/training_testing/testing/supplements/media/sport_rec_private_akts.pdf), a plastic overlay, a whiteboard marker, and an eraser to use for the chart mapping questions. You are also given a calculator for any simple calculations you may need to perform during the exam. I used the chart supplement for a large majority of the questions of my exam version and did not have any calculations to warrant me using the calculator. Overall, I felt decently prepared for the exam based on my studying.


## Results and License:

Once you finish your exam, the proctor will come get you from the test room, bring you back into the office, and let you know your score. If you pass, the proctor will give you your official paper with further instructions on how to go about getting your license. These are the steps to apply for your temporary sUAS pilot certificate: [Temporary Pilot Certificate](https://www.peltierphotocourses.com/pages/after-passing-part-107-test-iacra). Once you follow these steps, you have to wait until the email with your temporary certificate is sent to you before you may fly under Part 107 regulations. This email can take up to 4 weeks, however mine came back as early as 6 days so it just depends on how fast the information gets processed. After this, you may begin flying under Part 107 using your temporary certificate until your permanent license gets sent in the mail to you, which can take up to 2 months.

If you did not pass the exam, you can retake the exam after 14 days. After your exam, your proctor will give you your score sheet with the topic areas that you missed listed on top. I’d recommend going back over those areas as well as any other areas you struggled with or would like some refreshing on using some of the materials listed above.