# Studying For Part 107

*by Philana Ng*

Here is the link for instructions to sign up for the exam:
https://www.faa.gov/uas/commercial_operators/become_a_drone_pilot/

I passed the exam in November 2021 and will be writing about my experience. First off, I would recommend starting with [this video from Tony and Chelsea Northuo](https://www.youtube.com/watch?v=6_ucCKFJUCU&t=6s). This video gives a brief overview of all the topics that you will need to study. Do not trust the comments that state that they passed by only watching that video.

After watching the video, I would recommend memorizing
[Part 107 by the numbers](images\Part107_Numbers.pdf). Not on this list are the conditions at standard sea level (chapter 3b of study guide).  

Next, I will break down the official [FAA study guide](https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/media/remote_pilot_study_guide.pdf). Videos will only get you 50% of the way on the new exam. Sorry to say, but you will have to read some parts of this study guide.

**Chapter 2**: For each airspace class, know the ceiling and floor heights. This is very important for reading sectional charts. I had a question ask "Go 5 NM east of this point. What airspace are you in?". Do not assume anything. A solid red line is class C, but you could be above the ceiling, making it class E. For the special use airspaces and other airspace areas, understand what happens in each case. I had questions that asked "What would you expected in a restricted area" and "At what speeds should you expect military aircrafts to be at in Military Training Routes".

**Chapter 3**: Reading METARs and TAFs are relatively straightforward. I watched a few YouTube videos to figure it out. For the sky condition acronyms, you would only need to memorize the common ones. Chapter 3b is quite annoying because there is a lot of information in there, but the exam will only choose a few topics. Topics that should definitely be on there are density altitude, stable/unstable air, and clouds. The rest is just the luck of the draw. 15% of my exam was about this section.

**Chapter 4**: This is similar to chapter 3b where they throw a bunch of different information at you and only select a few on the exam. Things to note from this chapter are how CP and CG positioning changes the nose direction, effects of weight on performance, and calculating load factor.  

**Chapter 5**: This chapter is short, so I'd say to just read it.

**Chapter 7**: I got two questions from this section. One was about the military alphabet and the other was about frequencies.

**Chapter 9**: Memorize the definitions to a tee--things like causes, symptoms, effects on PIC, and what the PIC should do. Some questions will give you different scenarios and ask you what the best solution is. One scenario my colleague got was "You just drank a bottle of beer, but you feel fine. What should should you do?".

**Chapter 10**: My main mistakes in the exam were from this section. This was because all the YouTube study guides I watched passed this section. From this section, I got questions on the steps of decision making, assessing and mitigating risk, hazardous attitudes, etc. This is another section I would study up on.    

Depending on your exam, I would say chapter 9 and 10 make up 25% of the exam.

**Chapter 11**: Sectional charts cover about 30% of your exam. I would say
 to just watch video after video to understand this. They will ask a lot of questions about airspace, ceilings, floors, finding certain landmarks, etc. Check this video out to see if you got tricked https://www.youtube.com/watch?v=21b9hODOhGc
.If you did, I would recommend studying more. 

As of 2021, the FAA has included new questions on flight over people and remote identification (I got 4 questions on these). None of the study guides or YouTube videos online had these questions. I had to read through the two links provided by the FAA. 

https://www.faa.gov/uas/commercial_operators/operations_over_people/
https://www.faa.gov/uas/getting_started/remote_id/

I HIGHLY recommend that you take this practice exam to get a rough estimate on what score you will get. 
https://3drobotics.com/quiz/faa-part-107/

Then watch the explanation video. 
https://www.youtube.com/watch?v=-IEjiWiFf5E&t=0s

Even after I prepared for the exam, there were still questions that I was not prepared for. When I checked the FAA study guide, sure enough, the answer was there. You don't have to read the entire study guide, but I would recommended skimming it. Remember to take you time. Two hours gives you plenty of time to think. Bookmark the problems you are not sure of. Good luck!

